### PR TITLE
Added H6138 to the list of supported devices

### PR DESCRIPTION
**Pull request by rsiv**
Nice work!
Tested with Govee H6138 - works well.
Setup was a breeze and the light worked right away.

### CODE REVIEW

**Comment by hardcpp** [comment]
Hey thanks for testing :)

Glad it worked for you, i'm still improving it and will add more info about linux config tweaks.
Thanks for all the typos fix!

**Comment by rsiv** [comment]
Sure thing! 
Would you like to move the config values to a separate file, e.g. config.yaml?
I can then add docker support for easier deployment.

**Comment by hardcpp** [comment]
i  started added command line support -z/--zone -a/--adapter i still need to add mqtt support but it could be on top of a config file, in my case i use command line args because i run 3 bluetooth dongles for 10 lights so no need to clone multiple time the repo.

Docker can be an bonus if we can get as an option. I'm sadly a noob when it come to docker ^^

Do you have discord by any chance?

**Comment by rsiv** [comment]
I'm curious, why do you need 3 dongles? Is it to cover a large area?

The easiest way would probably be to have a single command line argument to specify the config file, and then you can have multiple config files will have zone, adapter, mqtt settings. 

Docker support should be really really once the dynamic config is stored outside the source files. Then you can start multiple containers, each with its own config file.

Another idea is to support home assistant auto discovery. Instead of configuring manual mqtt entries on home assistant side, you can publish to discovery topics and then home assistant will automatically create the entities.

Sorry, no discord, but I can join one if you have.

**Pull request merged**
